version: '3'
services:
  selenium:
    image: selenium/standalone-firefox:latest
    ports:
      - 7903:7900
      - 4444:4444
    environment:
      SE_NODE_SESSION_TIMEOUT: 100000
      TZ: Asia/Tokyo
  python3:
    # image: python:3.8.10
    tty: true
    build: .
    volumes:
      - "./scripts:/root/meshi-datsu"
    environment:
      SELENIUM_URL: http://selenium:4444/wd/hub
      TZ: Asia/Tokyo
